### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by adamsmesher** [d3vzer0/reternal-quickstart#5]
```
[emulation/Frameworks/reternal-quickstart]$ docker-compose up -d --build                                                          *[development]
Starting reternal-quickstart_redis-service_1 ... done
Starting reternal-quickstart_mongodb_1       ... done
Starting reternal-quickstart_compiler_1      ... done
Starting reternal-quickstart_api-socket_1    ... done
Starting reternal-quickstart_c2_1            ... done
Starting reternal-quickstart_api_1           ... done
Starting reternal-quickstart_ui_1            ... done

[emulation/Frameworks/reternal-quickstart]$ python3 manage.py -a install -t all                                             *[development]
Username: admin
Password:
Role (User/Admin): Admin
{'result': 'created', 'message': 'Succesfully created user'}
{'result': 'success', 'message': 'Finished importing base commands'}
{'result': 'success', 'message': 'Finished loading Mitre techniques'}
emulation/Frameworks/reternal-quickstart/cli/imports/import_mapping.py:14: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_object = yaml.load(yamlfile)
{'result': 'success', 'message': 'Finished loading mapped techniques'}
{'result': 'success', 'message': 'Finished importing all objects'}

[emulation/Frameworks/reternal-quickstart]$
```

"Succesfully created user" but a cant login, i have - "Unable to login"

**Comment by adamsmesher** [comment]
additionally, i have:
`Access to XMLHttpRequest at 'http://127.0.0.1:5000/api/v1/login' from origin 'http://ternal.local' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.` in the Chrome dev tools

**Comment by d3vzer0** [comment]
Could be an issue with the CORS environment setting in the docker-compose file. Can you check if the **CORS_DOMAIN** key is set to the correct domain/host that you're visiting? :)

PS. I also updated quite a lot of issues, be sure to create a backup/copy of your compose file and pull the latest changes ^^

**Comment by adamsmesher** [comment]
Thank you for replying!
Now, i have fresh (without any changes) install, with default docker-compose file. And problem still present. I need to add domain to all containers to the hosts file ?...

**Comment by d3vzer0** [comment]
The CORS_DOMAIN key should only be needed for the API service :) However, it could be that your host is starting the old/previously built container. Try running the below commands to rebuild and recreate the containers:

- docker-compose stop
- docker-compose build
- docker-compose up -d --force-recreate

**Comment by d3vzer0** [comment]
Ps. I updated the install guide with some extra details: https://github.com/d3vzer0/reternal-quickstart/wiki/Install--Guide

**Comment by adamsmesher** [comment]
my current compose file:
<details><summary>docker-compose.yml</summary>
<p>

#### 

```version: '2'
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    networks:
    - rtn-backend
    ports:
    - 127.0.0.1:27017:27017
    volumes:
    - mongodb-data:/data/db
  redis-service:
    image: redis
    restart: unless-stopped
    networks:
    - rtn-backend
    ports:
    - 127.0.0.1:6379:6379
  api:
    build: ./backend
    depends_on:
    - mongodb
    - redis-service
    networks:
    - rtn-frontend
    - rtn-backend
    ports:
    - 127.0.0.1:5000:5000
    environment:
      JWT_SECRET: WcdVkn0qfoh5aEJzweLzOqkrr
      FLASK_SECRET: qovYUxjZIgTu6KpFQWwfK6xEs
      CORS_DOMAIN: http://localhost
      C2_DEST: http://localhost:9000/api/v1/ping
  api-socket:
    build: ./backend
    depends_on:
    - redis-service
    networks:
    - rtn-backend
    environment:
      JWT_SECRET: 4Ura5MSJmejuyOTGatifn6907
      FLASK_SECRET: atVVrBKmUruhlJfl5yWGagY0M
    command:
    - celery
    - -A
    - app.tasks.listener.celery
    - worker
    - -Q
    - api
  compiler:
    build: ./agent
    depends_on:
    - redis-service
    networks:
    - rtn-backend
  ui:
    build:
      context: ./ui
      args:
        VUE_APP_BASEAPI: http://127.0.0.1:5000/api/v1
        VUE_APP_SOCKETHOST: http://127.0.0.1:5000
    depends_on:
    - api
    networks:
    - rtn-frontend
    volumes:
    - ./navigator-reternal.json:/usr/share/nginx/html/mitre-navigator/assets/config.json
    ports:
    - 80:80
  c2:
    build: ./c2
    depends_on:
    - redis-service
    - mongodb
    environment:
      C2_SECRET: JrAzsTndludmDI4n8V2ob7Zu3
      C2_PORT: 9000
    networks:
    - rtn-backend
    ports:
    - 9000:9000
volumes:
  mongodb-data:
    driver: local
networks:
  rtn-frontend:
    driver: bridge
  rtn-backend:
    driver: bridge
```

</p>
</details>

docker-compose build
docker-compose up -d --force-recreate

and after that, create user and importing all objects:
```
[emulation/Frameworks/reternal-quickstart]$ python manage.py -a install -t all
Username: admin
Password:
Role (User/Admin): Admin
{'result': 'failed', 'message': 'User already exists'}
{'result': 'success', 'message': 'Finished importing base commands'}
{'result': 'success', 'message': 'Finished loading Mitre techniques'}
emulation/Frameworks/reternal-quickstart/cli/imports/import_mapping.py:14: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_object = yaml.load(yamlfile)
{'result': 'success', 'message': 'Finished loading mapped techniques'}
{'result': 'success', 'message': 'Finished importing all objects'}
```
...and i still have "Unable to login". What else am I going to do?

**Comment by d3vzer0** [comment]
Strange. Can you share your current compose config (without the secret keys) and the URL you're trying to visit?

**Comment by adamsmesher** [comment]
source of docker-compose.yml in previous message (spoiler, hide by markdown) :) url is: http://127.0.0.1

**Comment by d3vzer0** [comment]
Ah I totally missed it, my bad :) This may sounds strange, but I think the issue is that CORS_DOMAIN is set to 'http://localhost' while you're visiting 'http://127.0.0.1'. According to the CORS security policy you're supposed to originate from the 'localhost' domain which is different than '127.0.0.1' as seen by browsers. Can you try visiting http://localhost instead and see if it works?

PS. If all fails try setting CORS_DOMAIN to "*" and see if it works for now. Note that this isn't secure but we can rule out some options :)

**Comment by rowham** [comment]
Solution:
Just add *CORS Everywhere* extension to your browser.
Here you can find *CORS Everywhere* extension for Firefox: [https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/](url)

**Comment by adamsmesher** [comment]
Thanks all! Problem solved!

**Comment by d3vzer0** [comment]
> Thanks all! Problem solved!

Good to hear :) I'll clarify some of the CORS options on the Wiki ^^

**Comment by jordisk** [comment]
@d3vzer0 hi, I'm having the same problem. I'm unable to login successfully on the platform. I have changed de CORS domain but still not success to log in.
```
root@redTeamTools:/opt/reternal-quickstart# cat docker-compose.yml
version: '2'
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    networks:
    - rtn-backend
    ports:
    - 127.0.0.1:27017:27017
    volumes:
    - mongodb-data:/data/db
  redis-service:
    image: redis
    restart: unless-stopped
    networks:
    - rtn-backend
    ports:
    - 127.0.0.1:6379:6379
  api:
    build: ./backend
    depends_on:
    - mongodb
    - redis-service
    networks:
    - rtn-frontend
    - rtn-backend
    ports:
    - 127.0.0.1:5000:5000
    environment:
      JWT_SECRET: snNRR7tlKxi2t2Nw3FHT99Xu4
      FLASK_SECRET: mJ4wKJxQZBjBeEY9C6YnCHpMb
      CORS_DOMAIN: http://10.202.27.2
      C2_DEST: http://127.0.0.1:9000/api/v1/ping
  api-socket:
    build: ./backend
    depends_on:
    - redis-service
    networks:
    - rtn-backend
    environment:
      JWT_SECRET: n7TqTHo6JFCreoAYb9wliD4Gv
      FLASK_SECRET: m4BB59f90bmZX8pDYZSLSBemw
    command:
    - celery
    - -A
    - app.tasks.listener.celery
    - worker
    - -Q
    - api
  compiler:
    build: ./agent
    depends_on:
    - redis-service
    networks:
    - rtn-backend
  ui:
    build:
      context: ./ui
      args:
        VUE_APP_BASEAPI: http://127.0.0.1:5000/api/v1
        VUE_APP_SOCKETHOST: http://127.0.0.1:5000
    depends_on:
    - api
    networks:
    - rtn-frontend
    volumes:
    - ./navigator-reternal.json:/usr/share/nginx/html/mitre-navigator/assets/config.json
    ports:
    - 0.0.0.0:80:80
  c2:
    build: ./c2
    depends_on:
    - redis-service
    - mongodb
    environment:
      C2_SECRET: PJeOWqEWpZX6wFfFnYDHPvtWu
      C2_PORT: 9000
    networks:
    - rtn-backend
    ports:
    - 0.0.0.0:9000:9000
volumes:
  mongodb-data:
    driver: local
networks:
  rtn-frontend:
    driver: bridge
  rtn-backend:
    driver: bridge
```

**Comment by d3vzer0** [comment]
@jordisk Do you happen to have some details regarding the host/ip that is running the other services? Is that the host @ 10.202.27.2? If so, you will also have to change the following options in the compose file to match the proper IP:

C2_DEST
VUE_APP_BASEAPI
VUE_APP_SOCKETHOST

When this is the case and you changed the values, try rebuilding the containers :) Short howto can be found @ https://github.com/d3vzer0/reternal-quickstart/wiki/Rebuilding---Updating

**Comment by DefenceLogic** [comment]
Dear D3vzer0,

I have same issue as not being able to login.

I am running on Ubuntu 18.04, all docker containers are up.

Here is my docker-compose.yml

```
version: '2'
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    networks:
    - rtn-backend
    ports:
    - 172.16.4.176:27017:27017
    volumes:
    - mongodb-data:/data/db
  redis-service:
    image: redis
    restart: unless-stopped
    networks:
    - rtn-backend
    ports:
    - 172.16.4.176:6379:6379
  api:
    build: ./backend
    depends_on:
    - mongodb
    - redis-service
    networks:
    - rtn-frontend
    - rtn-backend
    ports:
    - 172.16.4.176:5000:5000
    environment:
      JWT_SECRET: ILFKLSDTrQLQQoLj04UDpCJL1
      FLASK_SECRET: m5AIBrBJlTKknnQpSeeGAP7jI
      CORS_DOMAIN: http://172.16.4.176
      C2_DEST: http://172.16.4.176:9000/api/v1/ping
  api-socket:
    build: ./backend
    depends_on:
    - redis-service
    networks:
    - rtn-backend
    environment:
      JWT_SECRET: nQUUvRLQ6FfWnfGtzmtOhmba0
      FLASK_SECRET: qZoJPy7vVCXCPhqiAAM9uU3Gf
    command:
    - celery
    - -A
    - app.tasks.listener.celery
    - worker
    - -Q
    - api
  compiler:
    build: ./agent
    depends_on:
    - redis-service
    networks:
    - rtn-backend
  ui:
    build:
      context: ./ui
      args:
        VUE_APP_BASEAPI: http://172.16.4.176:5000/api/v1
        VUE_APP_SOCKETHOST: http://172.16.4.176:5000
    depends_on:
    - api
    networks:
    - rtn-frontend
    volumes:
    - ./navigator-reternal.json:/usr/share/nginx/html/mitre-navigator/assets/config.json
    ports:
    - 172.16.4.176:80:80
  c2:
    build: ./c2
    depends_on:
    - redis-service
    - mongodb
    environment:
      C2_SECRET: XseYMSHUA4XYHEPS3GEd6aGM5
      C2_PORT: 9000
    networks:
    - rtn-backend
    ports:
    - 172.16.4.176:9000:9000
volumes:
  mongodb-data:
    driver: local
networks:
  rtn-frontend:
    driver: bridge
  rtn-backend:
    driver: bridge
```
Is there anything incorrect in there?

I have tried CORS anywhere extension but no luck.

I have a user on the system

Output of user creation

```
nihon@nihon-siem-dev:~/reternal-quickstart$ python3 manage.py -a install -t all
Username: tester
Password: 
Role (User/Admin): Admin
{'result': 'created', 'message': 'Succesfully created user'}
{'result': 'success', 'message': 'Finished importing base commands'}
{'result': 'success', 'message': 'Finished loading Mitre techniques'}
/home/nihon/reternal-quickstart/cli/imports/import_mapping.py:14: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_object = yaml.load(yamlfile)
{'result': 'success', 'message': 'Finished loading mapped techniques'}
{'result': 'success', 'message': 'Finished importing all objects'}
```
Any ideas?
